# Generated by Django 5.1.2 on 2024-10-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_upload_date_photo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
    ]
